"""
Django settings for visualization project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-snn(=+pw6b=&$n9ifgdsxpz%l&wsa!s!7d-ub2suc9m(758)xm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # "django.contrib.admin",
    # "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "app_admin",
    "app_customer",
    "app_file",
    "app_project",
    "app_user",
    "app_workspace",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "visualization.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

# this is the config for the path of page
TEMPLATE_PATHS = {
    # page for customer
    "home": "customer/home.html",
    "introduction": "customer/introduction.html",
    "models": "customer/models.html",
    "workspace": "customer/workspace.html",
    "support": "customer/support.html",
    "login-customer": "customer/login-customer.html",
    "register": "customer/register.html",
    # page for admin
    "admin-home": "admin/admin-home.html",
    # page for user
    "user-center": "user/user-center.html",
    # page for workspace
    "work-home": "worksapce/work-home.html",
    "overview": "worksapce/overview.html",
    "create": "worksapce/create.html",
    "history": "worksapce/history.html",
}


WSGI_APPLICATION = "visualization.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# DATABASE_ROUTERS = ["visualization.router_db.RouterDB"]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "visualization_db",
        "USER": "visualizer",
        "PASSWORD": "visualizer",
        "HOST": "localhost",
        "PORT": "3306",
    },
    # "visualization_django_db": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "visualization_django_db",
    #     "USER": "visualizer",
    #     "PASSWORD": "visualizer",
    #     "HOST": "localhost",
    #     "PORT": "3306",
    # },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# email config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "visualizermt@gmail.com"
EMAIL_HOST_PASSWORD = "kmmm zadq ubcr bkcr"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# only the page in this project can use <iframe>
X_FRAME_OPTIONS = "SAMEORIGIN"

# Ensure cookies are only sent over HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Prevent JavaScript from accessing cookies (protect against XSS attacks)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app']
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',  
]
